Repository AtlasRender/atlas-monitor, pull requests merged in 2020-12, with the labels that each got.

#189 Add redux for websocket
  .env.development
  .env.production
  package.json
  src/core/CoreEventDispatcher.ts
  src/core/WebSocketMessage.ts
  src/globals.ts
  src/index.tsx
  src/layout/MonitorLayout/MonitorLayout.tsx
  yarn.lock
Labels: dependencies, development

#191 [RenderJobsTable] Fixed jobs not being displayed.
  src/components/RenderJobsTable/RenderJobsTable.tsx
Labels: bug

#192 Submit job plugin
  package.json
  src/components/BooleanPluginField/BooleanPluginField.tsx
  src/components/BooleanPluginField/index.ts
  src/components/BooleanPluginField/styles.ts
  src/components/RenderJobCustomFields/FloatPluginField/FloatPluginField.tsx
  src/components/RenderJobCustomFields/FloatPluginField/index.ts
  src/components/RenderJobCustomFields/FloatPluginField/styles.ts
  src/components/RenderJobCustomFields/IntegerPluginField/IntegerPluginField.tsx
  src/components/RenderJobCustomFields/IntegerPluginField/index.ts
  src/components/RenderJobCustomFields/IntegerPluginField/styles.ts
  src/components/RenderJobCustomFields/StringPluginField/StringPluginField.tsx
  src/components/RenderJobCustomFields/StringPluginField/index.ts
  src/components/RenderJobCustomFields/StringPluginField/styles.ts
  src/components/SeparatorPluginField/SeparatorPluginField.tsx
  src/components/SeparatorPluginField/index.ts
  src/components/SeparatorPluginField/styles.ts
  src/entities/BooleanField.ts
  src/entities/SeparatorField.ts
  src/interfaces/Plugin.ts
  src/interfaces/PluginFull.ts
  src/interfaces/PluginPreview.ts
  src/views/OrganizationPageView/LocalComponents/DialogUser/DialogUser.tsx
  src/views/RenderJobsView/RenderJobsView.tsx
  src/views/SubmitPageView/LocalComponents/DialogPlugin/DialogPlugin.tsx
  src/views/SubmitPageView/LocalComponents/DialogPlugin/index.ts
  src/views/SubmitPageView/LocalComponents/DialogPlugin/styles.ts
  src/views/SubmitPageView/LocalComponents/PluginInput/PluginInput.tsx
  src/views/SubmitPageView/LocalComponents/PluginInput/index.ts
  src/views/SubmitPageView/LocalComponents/PluginInput/styles.ts
  src/views/SubmitPageView/SubmitPageView.tsx
  yarn.lock
Labels: development, enhancement

#195 Bug fixes
  .idea/codeStyles/codeStyleConfig.xml
  src/layout/MonitorLayout/styles.ts
  src/views/CreateOrganizationPageView/CreateOrganizationPageView.tsx
  src/views/SubmitPageView/SubmitPageView.tsx
  src/views/UserPageView/LocalComponents/TokensViewer/TokensViewer.tsx
  tsconfig.json
Labels: bug

#196 Adding core sync to jobs (Work In Progress)
  .env.development
  .idea/atlas-monitor.iml
  craco.config.js
  package.json
  src/components/RenderJobsTable/RenderJobsTable.tsx
Labels: development, refactoring

#197 Changed pathfinder-monitor to atlas-monitor.
  .idea/modules.xml
Labels: bug

#198 Fix bug with incorrect updating jobs on web socket.
  src/components/RenderJobsTable/RenderJobsTable.tsx
Labels: bug

#203 Create logs page
  src/components/LogField/LogField.tsx
  src/components/LogField/index.ts
  src/components/LogField/styles.ts
  src/components/MenuElement/MenuElement.tsx
  src/components/MenuElement/index.ts
  src/components/MenuElement/styles.ts
  src/components/RenderJobsTable/RenderJobsTable.tsx
  src/entities/ShortJobs.ts
  src/globals.ts
  src/index.css
  src/interfaces/Log.ts
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/RenderJobsDetailsView/LocalComponents/DialogTabs/DialogTaskTabs/DialogTaskTabs.tsx
  src/views/RenderJobsDetailsView/LocalComponents/DialogTabs/DialogTaskTabs/index.ts
  src/views/RenderJobsDetailsView/LocalComponents/DialogTabs/DialogTaskTabs/styles.ts
  src/views/RenderJobsDetailsView/LocalComponents/DialogTaskLogs/DialogTaskLogs.tsx
  src/views/RenderJobsDetailsView/LocalComponents/DialogTaskLogs/index.ts
  src/views/RenderJobsDetailsView/LocalComponents/DialogTaskLogs/styles.ts
  src/views/RenderJobsDetailsView/RenderJobsDetailsView.tsx
  src/views/RenderJobsDetailsView/Tabs/TasksTab/TasksTab.tsx
  src/views/SubmitPageView/SubmitPageView.tsx
  tsconfig.json
Labels: development

#204 Fix plugins creation
  src/views/CreatePluginPageView/CreatePluginPageView.tsx
  src/views/CreatePluginPageView/LocalComponents/DragableComponents/Folder/Folder.tsx
  src/views/CreatePluginPageView/LocalComponents/DragableListItem/DragableListItem.tsx
  src/views/CreatePluginPageView/LocalComponents/PluginCreation/PluginCreation.tsx
  src/views/CreatePluginPageView/LocalComponents/PluginFieldSettings/PluginFieldSettings.tsx
  src/views/RenderJobsDetailsView/LocalComponents/DialogTaskLogs/DialogTaskLogs.tsx
Labels: bug, development

#207 Delete slash on route.
  src/views/RenderJobsDetailsView/LocalComponents/DialogTaskLogs/DialogTaskLogs.tsx
  src/views/SubmitPageView/LocalComponents/DialogPlugin/DialogPlugin.tsx
Labels: bug

#208 Delete slash on route.
  src/views/SubmitPageView/SubmitPageView.tsx
Labels: bug

#209 Delete slash on route
  src/views/SubmitPageView/LocalComponents/PluginInput/PluginInput.tsx
Labels: bug

#210 Logs and Organization pages
  src/components/MenuElement/MenuElement.tsx
  src/components/RenderJobsTable/RenderJobsTable.tsx
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/OrganizationPageView/LocalComponents/DialogPluginInfo/DialogPluginInfo.tsx
  src/views/OrganizationPageView/LocalComponents/DialogPluginInfo/index.ts
  src/views/OrganizationPageView/LocalComponents/DialogPluginInfo/styles.ts
  src/views/OrganizationPageView/LocalComponents/DialogUser/DialogUser.tsx
  src/views/OrganizationPageView/LocalComponents/PluginComponent/PluginComponent.tsx
  src/views/OrganizationPageView/LocalComponents/PluginComponent/styles.ts
  src/views/OrganizationPageView/LocalComponents/TopicWithButton/TopicWithButton.tsx
  src/views/OrganizationPageView/LocalComponents/TopicWithButton/styles.ts
  src/views/OrganizationPageView/OrganizationPageView.tsx
  src/views/OrganizationPageView/styles.ts
  src/views/RenderJobsDetailsView/LocalComponents/DialogTaskLogs/DialogTaskLogs.tsx
Labels: development

#213 Create logs page and slave dialog
  src/components/RenderJobsTable/RenderJobsTable.tsx
  src/views/CreateOrganizationPageView/CreateOrganizationPageView.tsx
  src/views/CreatePluginPageView/CreatePluginPageView.tsx
  src/views/OrganizationPageView/LocalComponents/DialogSlave/DialogSlave.tsx
  src/views/OrganizationPageView/LocalComponents/DialogSlave/index.ts
  src/views/OrganizationPageView/LocalComponents/DialogSlave/styles.ts
  src/views/OrganizationPageView/OrganizationPageView.tsx
  src/views/RenderJobsDetailsView/LocalComponents/DialogTaskLogs/DialogTaskLogs.tsx
  src/views/RenderJobsDetailsView/RenderJobsDetailsView.tsx
  src/views/RenderJobsDetailsView/Tabs/TasksTab/TasksTab.tsx
  src/views/RenderJobsView/RenderJobsView.tsx
  src/views/SubmitPageView/LocalComponents/DialogPlugin/DialogPlugin.tsx
  src/views/SubmitPageView/LocalComponents/PluginInput/PluginInput.tsx
  src/views/SubmitPageView/SubmitPageView.tsx
  src/views/UserEditView/UserEditView.tsx
  src/views/UserPageView/LocalComponents/TokensViewer/TokensViewer.tsx
  src/views/UserPageView/UserPageView.tsx
Labels: development

#221 Create plugin development
  src/entities/StringField.ts
  src/views/CreatePluginPageView/CreatePluginPageView.tsx
  src/views/CreatePluginPageView/LocalComponents/DragableComponents/Folder/Folder.tsx
  src/views/CreatePluginPageView/LocalComponents/PluginCreation/PluginCreation.tsx
  src/views/CreatePluginPageView/LocalComponents/PluginFieldSettings/PluginFieldSettings.tsx
Labels: bug, development

#223 Event tasks and logs
  src/components/RenderJobsTable/RenderJobsTable.tsx
  src/entities/Task.ts
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/RenderJobsDetailsView/LocalComponents/DialogTaskLogs/DialogTaskLogs.tsx
  src/views/RenderJobsDetailsView/LocalComponents/DialogTaskLogs/styles.ts
  src/views/RenderJobsDetailsView/RenderJobsDetailsView.tsx
  src/views/RenderJobsDetailsView/Tabs/TasksTab/TasksTab.tsx
Labels: bug, development

#227 Fix route
  src/views/OrganizationPageView/OrganizationPageView.tsx
Labels: bug

#233 Fix bugs
  src/components/RenderJobsTable/RenderJobsTable.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/index.ts
  src/components/SearchBar/styles.ts
  src/interfaces/KeyPair.ts
  src/interfaces/RequestError.ts
  src/utils/ErrorHandler.ts
  src/views/AuthorizationPageView/AuthorizationPageView.tsx
  src/views/CreateOrganizationPageView/CreateOrganizationPageView.tsx
  src/views/CreatePluginPageView/CreatePluginPageView.tsx
  src/views/OrganizationPageView/LocalComponents/DialogAddUsers/DialogAddUsers.tsx
  src/views/OrganizationPageView/LocalComponents/DialogAddUsers/styles.ts
  src/views/OrganizationPageView/LocalComponents/DialogSlave/DialogSlave.tsx
  src/views/OrganizationPageView/OrganizationPageView.tsx
  src/views/RenderJobsDetailsView/LocalComponents/DialogTaskLogs/DialogTaskLogs.tsx
  src/views/RenderJobsDetailsView/RenderJobsDetailsView.tsx
  src/views/RenderJobsDetailsView/Tabs/TasksTab/TasksTab.tsx
  src/views/RenderJobsView/RenderJobsView.tsx
  src/views/SignUpPage/SignUpPage.tsx
  src/views/SubmitPageView/LocalComponents/DialogPlugin/DialogPlugin.tsx
  src/views/SubmitPageView/LocalComponents/PluginInput/PluginInput.tsx
  src/views/SubmitPageView/SubmitPageView.tsx
  src/views/UserEditView/UserEditView.tsx
  src/views/UserPageView/LocalComponents/TokensViewer/TokensViewer.tsx
  src/views/UserPageView/UserPageView.tsx
Labels: bug

#253 Adding roles on org creation and redirecting
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/CreateOrganizationPageView/CreateOrganizationPageView.tsx
Labels: bug, invalid

#254 Roles toggles scroll
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/DialogAddRoles.tsx
  src/views/OrganizationPageView/LocalComponents/RoleToggles/RoleToggles.tsx
  src/views/OrganizationPageView/LocalComponents/RoleToggles/styles.ts
  src/views/OrganizationPageView/OrganizationPageView.tsx
Labels: bug, invalid

#255 [MonitorLayout] removed org button on side panel
  src/layout/MonitorLayout/MonitorLayout.tsx
Labels: bug

#256 Bug fixes
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/layout/MonitorLayout/styles.ts
  src/views/CreateOrganizationPageView/CreateOrganizationPageView.tsx
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/DialogAddRoles.tsx
  src/views/OrganizationPageView/LocalComponents/DialogAddUsers/DialogAddUsers.tsx
Labels: bug, development

#257 Bug fixes part 2
  src/components/SearchBar/SearchBar.tsx
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/OrganizationPageView/LocalComponents/DialogUser/DialogUser.tsx
  src/views/OrganizationPageView/LocalComponents/PluginComponent/PluginComponent.tsx
  src/views/OrganizationPageView/LocalComponents/TopicWithButton/TopicWithButton.tsx
  src/views/OrganizationPageView/OrganizationPageView.tsx
Labels: bug, development

#258 Owner can do anything in his organization.
  src/views/OrganizationPageView/OrganizationPageView.tsx
Labels: bug

#259 Fatal bug on roles fix
  src/interfaces/DemoRole.ts
  src/interfaces/Role.ts
  src/views/CreateOrganizationPageView/CreateOrganizationPageView.tsx
  src/views/CreateOrganizationPageView/styles.ts
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/DialogAddRoles.tsx
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/styles.ts
  src/views/OrganizationPageView/OrganizationPageView.tsx
Labels: bug

#274 Fixing default role
  src/views/CreateOrganizationPageView/CreateOrganizationPageView.tsx
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/DialogAddRoles.tsx
  src/views/OrganizationPageView/OrganizationPageView.tsx
  src/views/UserPageView/LocalComponents/TokensViewer/TokensViewer.tsx
  src/views/UserPageView/LocalComponents/TokensViewer/styles.ts
Labels: bug

#279 Fix fatal error on page loading
  src/layout/MonitorLayout/MonitorLayout.tsx
Labels: bug

#280 Org plugin view
  package.json
  src/views/OrganizationPageView/LocalComponents/DialogPluginInfo/DialogPluginInfo.tsx
  src/views/OrganizationPageView/LocalComponents/DialogPluginInfo/styles.ts
  src/views/UserPageView/LocalComponents/TokensViewer/TokensViewer.tsx
  src/views/UserPageView/UserPageView.tsx
  yarn.lock
Labels: bug, development

#292 Add possibility to delete organization
  src/views/OrganizationPageView/LocalComponents/TopicWithButton/TopicWithButton.tsx
  src/views/OrganizationPageView/OrganizationPageView.tsx
Labels: development

#294 Bug fixes
  src/components/ColorPicker/ColorPicker.tsx
  src/components/RenderJobCustomFields/FloatPluginField/FloatPluginField.tsx
  src/components/RenderJobCustomFields/IntegerPluginField/IntegerPluginField.tsx
  src/views/CreatePluginPageView/CreatePluginPageView.tsx
  src/views/CreatePluginPageView/LocalComponents/DragableListItem/DragableListItem.tsx
  src/views/CreatePluginPageView/LocalComponents/PluginCreation/PluginCreation.tsx
  src/views/CreatePluginPageView/LocalComponents/PluginFieldSettings/PluginFieldSettings.tsx
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/DialogAddRoles.tsx
  src/views/OrganizationPageView/LocalComponents/DialogUser/DialogUser.tsx
  src/views/OrganizationPageView/OrganizationPageView.tsx
Labels: bug, development

#295 Fix bug with plugins
  src/views/SubmitPageView/LocalComponents/DialogPlugin/DialogPlugin.tsx
  src/views/SubmitPageView/SubmitPageView.tsx
Labels: bug

#296 Minor styles fix
  src/views/CreateOrganizationPageView/CreateOrganizationPageView.tsx
  src/views/CreateOrganizationPageView/styles.ts
  src/views/OrganizationPageView/LocalComponents/DialogAddUsers/DialogAddUsers.tsx
  src/views/OrganizationPageView/LocalComponents/DialogAddUsers/styles.ts
  src/views/SubmitPageView/LocalComponents/DialogPlugin/styles.ts
Labels: bug
