Repository AtlasRender/atlas-monitor, pull requests merged in 2020-10, with the labels that each got.

#38 Connect User Page to Core
  .idea/dataSources.local.xml
  .idea/dataSources.xml
  src/hooks/useAuth.tsx
  src/hooks/useCoreRequest.ts
  src/views/OrganizationPageView/OrganizationPageView.tsx
  src/views/SignUpPage/SignUpPage.tsx
  src/views/UserPageView/UserPageView.tsx
Labels: development

#39 Added nojekyll.
  public/.nojekyll
Labels: development

#40 Added 404.html
  package.json
  public/404.html
  public/index.html
Labels: development

#46 Completed pages creation
  src/views/SubmitPageView/SubmitPageView.tsx
  src/views/SubmitPageView/styles.ts
Labels: development

#49 Submit Page grid changes
  src/views/SubmitPageView/SubmitPageView.tsx
  src/views/SubmitPageView/styles.ts
Labels: bug, development

#62 [env] Added core url to production env.
  .env.production
Labels: bug, development

#63 [env] Changed connection to https in production env.
  .env.production
Labels: bug, invalid

#103 Connected roles to core
  src/components/ColorPicker/ColorPicker.tsx
  src/components/ColorPicker/index.ts
  src/components/ColorPicker/styles.ts
  src/hooks/useConfirm.tsx
  src/index.tsx
  src/interfaces/Role.ts
  src/interfaces/UserData.ts
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/AuthorizationPageView/AuthorizationPageView.tsx
  src/views/CreateOrganizationPageView/CreateOrganizationPageView.tsx
  src/views/CreateOrganizationPageView/index.ts
  src/views/CreateOrganizationPageView/styles.ts
  src/views/OrganizationPageView/LocalComponents/AddRoleField/AddRoleField.tsx
  src/views/OrganizationPageView/LocalComponents/AddRoleField/index.ts
  src/views/OrganizationPageView/LocalComponents/AddRoleField/styles.ts
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/DialogAddRoles.tsx
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/index.ts
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/styles.ts
  src/views/OrganizationPageView/LocalComponents/DialogAddUsers/DialogAddUsers.tsx
  src/views/OrganizationPageView/LocalComponents/DialogAddUsers/index.ts
  src/views/OrganizationPageView/LocalComponents/DialogAddUsers/styles.ts
  src/views/OrganizationPageView/LocalComponents/DialogUser/DialogUser.tsx
  src/views/OrganizationPageView/LocalComponents/DialogUser/index.ts
  src/views/OrganizationPageView/LocalComponents/DialogUser/styles.ts
  src/views/OrganizationPageView/OrganizationPageView.tsx
  src/views/OrganizationPageView/styles.ts
  src/views/SignUpPage/SignUpPage.tsx
  src/views/UserPageView/LocalComponents/TokensViewer/TokensViewer.tsx
  src/views/UserPageView/UserPageView.tsx
  yarn.lock
Labels: development

#106 Org creation page
  src/views/CreateOrganizationPageView/CreateOrganizationPageView.tsx
  src/views/CreateOrganizationPageView/styles.ts
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/DialogAddRoles.tsx
  src/views/OrganizationPageView/OrganizationPageView.tsx
Labels: development

#114 Organization page development
  src/components/ColorPicker/ColorPicker.tsx
  src/components/DataTextField/DataTextField.tsx
  src/components/Loading/Loading.tsx
  src/components/Loading/index.ts
  src/components/Loading/styles.ts
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/DialogAddRoles.tsx
  src/views/OrganizationPageView/LocalComponents/OpportunitiesPicker/OpportunitiesPicker.tsx
  src/views/OrganizationPageView/LocalComponents/OpportunitiesPicker/index.ts
  src/views/OrganizationPageView/LocalComponents/OpportunitiesPicker/styles.ts
  src/views/OrganizationPageView/LocalComponents/PluginComponent/PluginComponent.tsx
  src/views/OrganizationPageView/OrganizationPageView.tsx
  src/views/OrganizationPageView/styles.ts
  src/views/UserPageView/LocalComponents/OrganizationsFieldsRow/OrganizationsFieldsRow.tsx
  src/views/UserPageView/LocalComponents/OrganizationsFieldsRow/styles.ts
  src/views/UserPageView/LocalComponents/TokensViewer/TokensViewer.tsx
  src/views/UserPageView/LocalComponents/TokensViewer/styles.ts
  src/views/UserPageView/UserPageView.tsx
  src/views/UserPageView/styles.ts
Labels: development
