Repository AtlasRender/atlas-monitor, pull requests merged in 2020-11, with the labels that each got.

#119 Changed REACT_APP_CORE_URL
  .env.development
Labels: development

#121 Provided auto logout if smth go wrong.
  src/hooks/useAuth.tsx
  src/layout/ChooseLayout/ChooseLayout.tsx
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/RenderJobsView/RenderJobsView.tsx
Labels: development

#122 [env] Changed origin address.
  .env.development
Labels: development, rest

#125 Bug fixes and User dialog modify
  .env.development
  src/layout/MainPageLayout/MainPageLayout.tsx
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/DialogAddRoles.tsx
  src/views/OrganizationPageView/LocalComponents/DialogUser/DialogUser.tsx
  src/views/OrganizationPageView/LocalComponents/DialogUser/styles.ts
  src/views/OrganizationPageView/OrganizationPageView.tsx
Labels: bug, development

#126 Add roles fix
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/DialogAddRoles.tsx
  src/views/OrganizationPageView/OrganizationPageView.tsx
Labels: bug

#127 Dialog User development.
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/DialogAddRoles.tsx
  src/views/OrganizationPageView/LocalComponents/DialogUser/DialogUser.tsx
  src/views/OrganizationPageView/LocalComponents/DialogUser/styles.ts
  src/views/OrganizationPageView/OrganizationPageView.tsx
  src/views/OrganizationPageView/styles.ts
Labels: development

#129 Created full height borders and text overflow.
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/OrganizationPageView/LocalComponents/DialogUser/DialogUser.tsx
  src/views/OrganizationPageView/LocalComponents/DialogUser/styles.ts
  src/views/OrganizationPageView/OrganizationPageView.tsx
  src/views/OrganizationPageView/styles.ts
Labels: bug, development

#130 User Edit Page Creation
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/UserEditView/UserEditView.tsx
  src/views/UserEditView/index.ts
  src/views/UserEditView/styles.ts
  src/views/UserPageView/UserPageView.tsx
  src/views/UserPageView/styles.ts
Labels: development

#131 Render Jobs Page development.
  src/components/RenderJobsTable/RenderJobsTable.tsx
  src/entities/RenderJob.ts
  src/entities/ShortJobs.ts
  src/interfaces/Jobs.ts
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/RenderJobsDetailsView/RenderJobsDetailsView.tsx
  src/views/RenderJobsView/RenderJobsView.tsx
Labels: development

#133 [Layout] Added atlas image.
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/layout/MonitorLayout/images/AtlasSystemsLogo.svg
Labels: development

#137 Edit user page and Render job details page development
  src/components/RenderJobsTable/RenderJobsTable.tsx
  src/entities/Task.ts
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/AuthorizationPageView/AuthorizationPageView.tsx
  src/views/RenderJobsDetailsView/RenderJobsDetailsView.tsx
  src/views/RenderJobsDetailsView/Tabs/TasksTab/TasksTab.tsx
  src/views/RenderJobsView/RenderJobsView.tsx
  src/views/UserEditView/UserEditView.tsx
  src/views/UserEditView/styles.ts
  src/views/UserPageView/UserPageView.tsx
Labels: development

#138 Submit Job
  package.json
  src/components/RenderJobsTable/RenderJobsTable.tsx
  src/entities/RenderJob.ts
  src/entities/ShortJobs.ts
  src/entities/Task.ts
  src/interfaces/Jobs.ts
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/layout/MonitorLayout/images/AtlasSystemsLogo.svg
  src/views/AuthorizationPageView/AuthorizationPageView.tsx
  src/views/RenderJobsDetailsView/RenderJobsDetailsView.tsx
  src/views/RenderJobsDetailsView/Tabs/TasksTab/TasksTab.tsx
  src/views/RenderJobsView/RenderJobsView.tsx
  src/views/UserEditView/UserEditView.tsx
  src/views/UserEditView/styles.ts
  src/views/UserPageView/UserPageView.tsx
  src/views/UserPageView/githubAvatar.jpg
  yarn.lock
Labels: development, enhancement

#139 Submit job dev
  src/views/SubmitPageView/SubmitPageView.tsx
  src/views/SubmitPageView/styles.ts
Labels: development, enhancement

#141 Render Jobs Pages development and Bug Fixes
  src/components/RenderJobsTable/RenderJobsTable.tsx
  src/components/RenderJobsTable/styles.ts
  src/views/RenderJobsDetailsView/RenderJobsDetailsView.tsx
  src/views/RenderJobsDetailsView/Tabs/TasksTab/TasksTab.tsx
  src/views/RenderJobsDetailsView/Tabs/TasksTab/styles.ts
  src/views/RenderJobsDetailsView/styles.ts
  src/views/RenderJobsView/RenderJobsView.tsx
  src/views/RenderJobsView/styles.ts
  src/views/UserEditView/UserEditView.tsx
  src/views/UserPageView/UserPageView.tsx
  src/views/UserPageView/styles.ts
Labels: development

#145 Submit job dev
  src/views/SubmitPageView/SubmitPageView.tsx
Labels: development

#143 Change altals colors
  src/components/DataTextField/DataTextField.test.tsx
  src/components/DataTextField/DataTextField.tsx
  src/components/DataTextField/styles.ts
  src/components/Header/Header.tsx
  src/components/Header/styles.ts
  src/components/RenderJobsTable/RenderJobsTable.tsx
  src/components/RenderJobsTable/styles.ts
  src/index.tsx
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/layout/MonitorLayout/styles.ts
  src/theme.ts
  src/views/OrganizationPageView/LocalComponents/DialogAddRoles/DialogAddRoles.tsx
  src/views/RenderJobsDetailsView/Tabs/InfoTab/InfoTab.tsx
  src/views/RenderJobsDetailsView/Tabs/TasksTab/TasksTab.tsx
  src/views/RenderJobsDetailsView/Tabs/TasksTab/styles.ts
Labels: development

#152 Plugin Page development
  src/entities/BasicPluginField.ts
  src/entities/InputField.ts
  src/entities/Organization.ts
  src/entities/ShortJobs.ts
  src/entities/Task.ts
  src/entities/UserToken.ts
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/CreatePluginPageView/CreatePluginPageView.tsx
  src/views/CreatePluginPageView/LocalComponents/DialogPlugin/DialogPlugin.tsx
  src/views/CreatePluginPageView/LocalComponents/DialogPlugin/index.ts
  src/views/CreatePluginPageView/LocalComponents/DialogPlugin/styles.ts
  src/views/CreatePluginPageView/index.ts
  src/views/CreatePluginPageView/styles.ts
Labels: development

#144 Org creation page
  src/views/CreateOrganizationPageView/CreateOrganizationPageView.tsx
Labels: development, enhancement

#154 Fix small bugs
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/AuthorizationPageView/AuthorizationPageView.tsx
  src/views/OrganizationPageView/LocalComponents/TopicWithButton/TopicWithButton.tsx
  src/views/OrganizationPageView/OrganizationPageView.tsx
  src/views/SignUpPage/SignUpPage.tsx
  src/views/UserPageView/UserPageView.tsx
Labels: bug

#155 Create file uploader component
  .env.development
  .idea/runConfigurations/npm_start.xml
  package.json
  src/components/FilesLoader/FilesLoader.tsx
  src/components/FilesLoader/index.ts
  src/components/FilesLoader/styles.ts
  src/entities/TempFile.ts
  src/views/OrganizationPageView/OrganizationPageView.tsx
  yarn.lock
Labels: dependencies, development, rest

#158 [Rest] Removed preset header Content-Type.
  src/components/FilesLoader/FilesLoader.tsx
  src/hooks/useCoreRequest.ts
  src/utils/Rest.ts
  src/views/OrganizationPageView/OrganizationPageView.tsx
Labels: bug, rest

#160 Plugin Page development
  src/entities/BasicPluginField.ts
  src/entities/InputField.ts
  src/views/CreatePluginPageView/CreatePluginPageView.tsx
  src/views/CreatePluginPageView/LocalComponents/DialogPlugin/DialogPlugin.tsx
  src/views/CreatePluginPageView/LocalComponents/DialogPlugin/styles.ts
Labels: development

#162 Plugin Page development
  src/views/CreatePluginPageView/CreatePluginPageView.tsx
  src/views/CreatePluginPageView/LocalComponents/DialogPlugin/DialogPlugin.tsx
Labels: development

#163 Adding file uploader to plugins
  package.json
  src/components/FilesLoader/FilesLoader.tsx
  src/components/FilesLoader/styles.ts
  src/views/CreatePluginPageView/CreatePluginPageView.tsx
  yarn.lock
Labels: dependencies, development

#167 Drag n drop
  package.json
  src/entities/InputField.ts
  src/index.tsx
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/utils/IdGenerator.ts
  src/views/CreatePluginPageView/CreatePluginPageView.tsx
  src/views/CreatePluginPageView/LocalComponents/DialogPlugin/DialogPlugin.tsx
  src/views/CreatePluginPageView/LocalComponents/DragableListItem/DragableListItem.tsx
  src/views/CreatePluginPageView/LocalComponents/DragableListItem/index.ts
  src/views/CreatePluginPageView/LocalComponents/DragableListItem/styles.ts
  yarn.lock
Labels: bug, development

#169 Fixed bugs
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/UserPageView/LocalComponents/TokensViewer/TokensViewer.tsx
Labels: bug

#183 Plugin constructor
  package.json
  src/components/FilesLoader/FilesLoader.tsx
  src/entities/BasicPluginField.ts
  src/entities/BooleanField.ts
  src/entities/FloatField.ts
  src/entities/GroupField.ts
  src/entities/IntegerField.ts
  src/entities/SeparatorField.ts
  src/entities/StringField.ts
  src/hooks/usePluginContext.ts
  src/layout/ChooseLayout/ChooseLayout.tsx
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/views/CreateOrganizationPageView/CreateOrganizationPageView.tsx
  src/views/CreatePluginPageView/CreatePluginPageView.tsx
  src/views/CreatePluginPageView/LocalComponents/DialogPlugin/DialogPlugin.tsx
  src/views/CreatePluginPageView/LocalComponents/DragableComponents/DragableSubject/DragableSubject.tsx
  src/views/CreatePluginPageView/LocalComponents/DragableComponents/DragableSubject/index.ts
  src/views/CreatePluginPageView/LocalComponents/DragableComponents/DragableSubject/styles.ts
  src/views/CreatePluginPageView/LocalComponents/DragableComponents/Folder/Folder.tsx
  src/views/CreatePluginPageView/LocalComponents/DragableComponents/Folder/index.ts
  src/views/CreatePluginPageView/LocalComponents/DragableComponents/Folder/styles.ts
  src/views/CreatePluginPageView/LocalComponents/DragableListItem/DragableListItem.tsx
  src/views/CreatePluginPageView/LocalComponents/PluginCreation/PluginCreation.tsx
  src/views/CreatePluginPageView/LocalComponents/PluginCreation/index.ts
  src/views/CreatePluginPageView/LocalComponents/PluginCreation/styles.ts
  src/views/CreatePluginPageView/LocalComponents/PluginFieldSettings/PluginFieldSettings.tsx
  src/views/CreatePluginPageView/LocalComponents/PluginFieldSettings/index.ts
  src/views/CreatePluginPageView/LocalComponents/PluginFieldSettings/styles.ts
  src/views/OrganizationPageView/LocalComponents/DialogUser/DialogUser.tsx
  src/views/OrganizationPageView/OrganizationPageView.tsx
Labels: dependencies, development, enhancement, entity, rest

#184 Fix bugs with new react sripts
  .gitignore
  package.json
  src/components/DataTextField/DataTextField.tsx
  src/layout/ChooseLayout/ChooseLayout.tsx
  src/layout/MonitorLayout/MonitorLayout.tsx
  src/layout/MonitorLayout/styles.ts
  tsconfig.json
  yarn.lock
Labels: bug, development

#187 Show new render jobs
  src/components/Progress/Progress.tsx
  src/components/RenderJobsTable/RenderJobsTable.tsx
  src/entities/ShortJobs.ts
  src/views/RenderJobsDetailsView/RenderJobsDetailsView.tsx
  src/views/RenderJobsDetailsView/Tabs/TasksTab/TasksTab.tsx
Labels: development
